[project]
name = "authenticationpractice"
version = "0.1.0"
description = "FastAPI API built to practice web authentication mechanisms"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.5",
    "fastapi[standard]>=0.128.8",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.7",
    "psycopg2-binary>=2.9.12",
    "psycopg[binary]>=3.3.4",
    "pytest>=9.1.1",
    "pytest-postgresql>=8.1.0",
    "python-dotenv>=1.2.2",
    "sqlalchemy>=2.0.51",
    "uuid6>=2025.0.1",
]
