"""Add INSERT permisssions on users table to playground_user_1

Revision ID: 59e1478aebac
Revises: 635e74f7301c
Create Date: 2026-09-25 16:03:06.970030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e1478aebac'
down_revision: Union[str, Sequence[str], None] = '635e74f7301c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("GRANT INSERT (first_name, last_name, username, password, email, phone, dob, address, city, state, zipcode, country, company) ON users TO playground_user_1")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("REVOKE INSERT ON users TO playground_user_1")
    # ### end Alembic commands ###
