"""add missing INSERT permissions on necessary tables

Revision ID: 9676992bcb6d
Revises: 59e1478aebac
Create Date: 2026-09-26 12:22:41.611811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9676992bcb6d'
down_revision: Union[str, Sequence[str], None] = '59e1478aebac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("GRANT INSERT (name, type) ON accounts TO playground_user_1")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("REVOKE INSERT ON accounts TO playground_user_1")
    # ### end Alembic commands ###
