"""Added email_verified to users table

Revision ID: 0947b49f4b53
Revises: 3d54fa0e487f
Create Date: 2026-09-03 15:13:06.930236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0947b49f4b53'
down_revision: Union[str, Sequence[str], None] = '3d54fa0e487f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('users', 'dob',
               existing_type=sa.DATE(),
               nullable=True)

    op.drop_column("users", "email_verified", if_exists=True) # Messed up migration files (placed changes in 3d54fa0e487f versus 0947b49f4b53). Fixed. Need this line as guard for any overlap from mistake

    op.add_column("users", sa.Column("email_verified", sa.Boolean, server_default=sa.false(), nullable=False))

    # Drop duplication triggers and functions
    op.execute("DROP FUNCTION IF EXISTS reset_email_verified_on_change()")
    op.execute("DROP TRIGGER IF EXISTS trg_update_email_verified ON users")

    # Grant playground_user_1 permission to select email_verified on users table
    op.execute("GRANT SELECT (email_verified) ON users TO playground_user_1")

    # Functions and triggers to update email verified
    # 1. User creates account and verifies email. Subsequent attempts to change email_verified are blocked
    # 2. Special case: user updates email. Email needs to be reverified. email_verified reverted to false
    op.execute("""
               CREATE FUNCTION reset_email_verified_on_change()
                   RETURNS trigger
                   LANGUAGE plpgsql
            AS $$
               BEGIN
                    IF
               NEW.email IS DISTINCT FROM OLD.email THEN
                        NEW.email_verified = false;
               END IF;
               RETURN NEW;
               END;
            $$
               """)

    op.execute("""
               CREATE TRIGGER trg_update_email_verified
                   BEFORE UPDATE
                   ON users
                   FOR EACH ROW
                   EXECUTE FUNCTION reset_email_verified_on_change()
               """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop triggers and functions for email_verified
    op.execute("DROP FUNCTION IF EXISTS reset_email_verified_on_change()")
    op.execute("DROP TRIGGER IF EXISTS trg_update_email_verified ON users")

    # Revoke playground_app permission to select email_verified on users table
    op.execute('REVOKE SELECT (email_verified) ON users FROM playground_user_1')

    op.alter_column('users', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
