"""add missing INSERT permissions on necessary tables

Revision ID: 9676992bcb6d
Revises: 59e1478aebac
Create Date: 2026-09-26 12:22:41.611811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9676992bcb6d'
down_revision: Union[str, Sequence[str], None] = '59e1478aebac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("GRANT INSERT (name, type) ON accounts TO playground_user_1")

    # Revoke currently granted update permission, because we're moving to security definer functions to update tokens
    op.execute("REVOKE UPDATE ON email_verifications FROM playground_user_1")
    op.execute("REVOKE UPDATE ON password_resets FROM playground_user_1")

    # Remove unnecessary RLS functions
    op.execute("DROP POLICY IF EXISTS update_own_email_verifications ON email_verifications")
    op.execute("DROP POLICY IF EXISTS update_own_password_resets ON password_resets")

    # Remove potential duplication functions
    op.execute("DROP FUNCTION IF EXISTS verify_email_verification_token(text)")
    op.execute("DROP FUNCTION IF EXISTS verify_password_reset_token(text)")

    op.execute("""
        CREATE FUNCTION verify_email_verification_token(p_token_hash text)
        RETURNS boolean
        SECURITY DEFINER
        SET search_path = public
        AS $$
        BEGIN
            UPDATE email_verifications
            SET used_at = NOW()
            WHERE token = p_token_hash
            AND used_at IS NULL
            AND expires_at > NOW();
            RETURN FOUND;
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("GRANT EXECUTE ON FUNCTION verify_email_verification_token(text) TO playground_user_1")

    op.execute("""
        CREATE FUNCTION verify_password_reset_token(p_token_hash text)
        RETURNS boolean
        SECURITY DEFINER
        SET search_path = public
        AS $$
        BEGIN
            UPDATE password_resets
            SET used_at = NOW()
            WHERE token = p_token_hash
            AND used_at IS NULL
            AND expires_at > NOW();
            RETURN FOUND;
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("GRANT EXECUTE ON FUNCTION verify_password_reset_token(text) TO playground_user_1")

    op.execute("""
        CREATE FUNCTION insert_email_verification_token(p_user_id integer, p_token_hash text)
            RETURNS BOOLEAN 
            SECURITY DEFINER
            SET search_path = public
            LANGUAGE plpgsql
        AS $$
            BEGIN
                INSERT INTO email_verifications (user_id, token)
                VALUES (p_user_id, p_token_hash);

                RETURN TRUE;
            EXCEPTION
                WHEN OTHERS THEN
                    RETURN FALSE;
            END;
        $$;
    """)

    op.execute("GRANT EXECUTE ON FUNCTION insert_email_verification_token(integer, text) TO playground_user_1")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("REVOKE INSERT ON accounts TO playground_user_1")

    op.execute("GRANT UPDATE (used_at) ON email_verifications TO playground_user_1")
    op.execute("GRANT UPDATE (used_at) ON password_resets TO playground_user_1")

    op.execute("DROP FUNCTION IF EXISTS verify_email_verification_token(text)")
    op.execute("DROP FUNCTION IF EXISTS verify_password_reset_token(text)")
    op.execute("DROP FUNCTION IF EXISTS insert_email_verification_token(integer, text)")

    op.execute("CREATE POLICY update_own_email_verifications ON email_verifications FOR UPDATE TO playground_user_1 USING (user_id = current_setting('app.current_user_id', true)::integer)")
    op.execute("CREATE POLICY update_own_password_resets ON password_resets FOR UPDATE TO playground_user_1 USING (user_id = current_setting('app.current_user_id', true)::integer)")
    # ### end Alembic commands ###
